/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertshiftarray;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void insertArrayAndValue_With_EvenLength_ReturnUpdatedArray() {
        Library sut = new Library();
        int [] actual = sut.insertShiftArray(new int[] {5,1,6,8},9);
        Assertions.assertArrayEquals(new int[] {5,1,9,6,8},actual) ;
    }
    @Test void insertArrayAndValue_With_OddLength_ReturnUpdatedArray() {
        Library sut = new Library();
        int [] actual = sut.insertShiftArray(new int[] {42,8,15,23,42},16);
        Assertions.assertArrayEquals(new int[] {42,8,15,16,23,42},actual) ;
    }
}
