/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.List;

public class App {

    public static void main(String[] args) {
        Graph graph = new Graph();

        graph.addVertex("Mohammad");
        graph.addVertex("Jehad");
        graph.addVertex("Shanab");
        graph.addVertex("Yousef");

        graph.addEdge("Mohammad", "Yousef", 3);
        graph.addEdge("Mohammad", "Shanab", 4);
        graph.addEdge("Mohammad", "Jehad");

        System.out.println(graph.printGraph());
        System.out.println();
        System.out.println(graph.printGraph());
        System.out.println(graph.size());
        System.out.println(graph.getNeighbors("Yousef"));
        System.out.println();
        Graph citiesGraph = new Graph();
        citiesGraph.addVertex("London");
        citiesGraph.addVertex("Paris");
        citiesGraph.addVertex("Berlin");
        citiesGraph.addVertex("Rome");
        citiesGraph.addEdge("London", "Paris", 50);
        citiesGraph.addEdge("Paris", "Berlin", 40);
        citiesGraph.addEdge("Berlin", "Rome", 30);

        BusinessCalculator tripCalculator = new BusinessCalculator();
        String[] trip1 = {"London", "Paris", "Berlin", "Rome"};
        Integer cost1 = tripCalculator.businessTrip(citiesGraph, trip1);
        System.out.println("Cost of trip 1: " + cost1);
        String[] trip2 = {"London", "Rome"};
        Integer cost2 = tripCalculator.businessTrip(citiesGraph, trip2);
        System.out.println("Cost of trip 2: " + cost2);
        String[] trip3 = {"Berlin"};
        Integer cost3 = tripCalculator.businessTrip(citiesGraph, trip3);
        System.out.println("Cost of trip 3: " + cost3);

    }
}
