/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

    public static void main(String[] args) {
        Graph graph = new Graph();

        graph.addVertex("Mohammad");
        graph.addVertex("Jehad");
        graph.addVertex("Shanab");
        graph.addVertex("Yousef");

        graph.addEdge("Mohammad", "Yousef", 3);
        graph.addEdge("Mohammad", "Shanab", 4);
        graph.addEdge("Mohammad", "Jehad");

        System.out.println(graph.printGraph());
        System.out.println();
        System.out.println(graph.printGraph());
        System.out.println(graph.size());
        System.out.println(graph.getNeighbors("Yousef"));
        System.out.println();
    }
}
