/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import org.junit.jupiter.api.Test;
import sort.classes.MovieClass;
import sort.classes.MovieSorterClass;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    MovieSorterClass movieSort = new MovieSorterClass();

    @Test
    public void testSortMoviesByYear() {
        List<MovieClass> movies = Arrays.asList(
                new MovieClass("Movie1", 2010, null),
                new MovieClass("Movie2", 2005, null),
                new MovieClass("Movie3", 2020, null)
        );

        List<MovieClass> sortedMovies = movieSort.sortMovieByYear(movies);

        assertEquals("Movie3", sortedMovies.get(0).getTitle());
        assertEquals("Movie2", sortedMovies.get(2).getTitle());
    }
    @Test
    public void testSortMoviesByTitle() {
        List<MovieClass> movies = Arrays.asList(
                new MovieClass("Spy", 2000, null),
                new MovieClass("Fast and furious", 2015, null),
                new MovieClass("The Flight", 2020, null)
        );
        List<MovieClass> sortedMovies = movieSort.sortMovieByTitle(movies);
        assertEquals("Fast and furious", sortedMovies.get(0).getTitle());
        assertEquals("The Flight", sortedMovies.get(1).getTitle());
    }
}
