/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

public class App {

    public static void main(String[] args) {
        MergeSort mergesort = new MergeSort();
        int[] testArr = {8,4,23,42,16,15};
        mergesort.mergeSort(testArr);
        for (int num: testArr
             ) {
            System.out.println(num);
        }
    }
}
