/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HashTableTest {
    @Test
    public void givenAnEmptyHashTableReturnNull(){
        HashTable<String,Integer> hashTable = new HashTable<>();
        assertTrue(hashTable.keys().isEmpty());
        assertNull(hashTable.get("SortOfAKey"));
        assertFalse(hashTable.has("SortOfAKey"));
    }
    @Test
    public void givenAHashTableWithSomeDataReturnTheData(){
        HashTable<String,String> hashTable = new HashTable<>();

        hashTable.set("BIRTHDATE","1999");
        hashTable.set("CURRENCY","JOD");
        hashTable.set("NAME","MOHAMMAD");

        assertTrue(hashTable.has("BIRTHDATE"));
        assertTrue(hashTable.has("CURRENCY"));

        assertEquals("1999",hashTable.get("BIRTHDATE"));
        assertEquals("MOHAMMAD",hashTable.get("NAME"));
    }
    @Test
    public void givenAHashTableCheckForConsistentOfKeys(){
        HashTable<String,String> movieHashTable = new HashTable<>();
        movieHashTable.set("movieName","London Has Fallen");
        movieHashTable.set("movieRelease","2016");
        movieHashTable.set("movieStar","Gerard Butler");

        assertTrue(movieHashTable.has("movieName"));
        assertTrue(movieHashTable.has("movieStar"));
        assertTrue(movieHashTable.has("movieRelease"));
    }
    @Test
    public void givenAHashTableWithSomeCollision(){
        HashTable<String, Integer> hashtable = new HashTable<>(1);
        hashtable.set("a", 1);
        hashtable.set("a", 2);

        assertEquals(2, hashtable.get("a"));
    }
}
