/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matrix;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void matrixWithEmptyRows_ReturnZeros() {
        int[][] matrix = {
                {},
                {},
                {}
        };

        int[] expectedSum = {0, 0, 0};
        int[] actualSum = App.sumOfMatrix(matrix);

        assertArrayEquals(expectedSum, actualSum);
    }
    @Test
    public void matrixWithDifferentColumnCounts_Return_WithSummation() {
        int[][] matrix = {
                {1, 2},
                {3, 4, 5},
                {6, 7, 8, 9}
        };

        int[] expectedSum = {3, 12, 30};
        int[] actualSum = App.sumOfMatrix(matrix);

        assertArrayEquals(expectedSum, actualSum);
    }
}
