/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        BinarySearchTree<Integer> bst = new BinarySearchTree<>();
        bst.add(5); // root
        bst.add(4); // left child
        bst.add(9); // right child
        bst.add(3); // left of 4
        bst.add(15);// right of 9
        bst.add(22); // right of 22
        bst.add(19); // left of 22
        bst.add(18); // left of 19
        bst.add(8); // left of 9
        ArrayList<Integer> travel = new ArrayList<>();
//        System.out.println(bst.inOrderTraverse(bst.getRoot(),travel).toString()); // in order left >> root >> right >> output should be  >> [6,10,22,45,65]
        System.out.println(" Pre Order : " + bst.preOrderTraverse(bst.getRoot(),travel).toString());
        travel.clear();
        System.out.println(" Post Order : " + bst.postOrderTraverse(bst.getRoot(),travel).toString()); // left >> right >> root
//        System.out.println(bst.postOrderTraverse(bst.getRoot(),travel).toString());
        travel.clear();
        System.out.println(" In Order : " + bst.inOrderTraverse(bst.getRoot(),travel).toString()); // left >> root >> right
        System.out.println("Maximum : " + bst.findMaxValue());
        System.out.println("BFS : " + bst.breadthFirst());
    }
}
