/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matrix;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        int [][] matrix = {{1,2,3},{3,5,7},{1,7,10}};
        System.out.println(Arrays.toString(sumOfMatrix(matrix)));
    }
    public static int[] sumOfMatrix(int[][] matrix) {
        int [] sum = new int[matrix.length];
        for(int i =0; i<matrix.length;i++) {
            for(int j = 0 ; j< matrix[i].length;j++){
                sum[i] += matrix[i][j];
            }
        }
        return sum;
    }
}
