/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

public class App {

    public static void main(String[] args) {
        int[] sorted = {1,5,6,9,10};
        System.out.println("index of the target is " + binarySearch(sorted,6));
    }
    public static int binarySearch(int[] sortedArray,int target) {
        int left = 0;
        int right = sortedArray.length -1;
        while (left<=right) {
            int mid = (right+left) / 2;
            if (sortedArray[mid] == target) {
                return mid;
            } else if (sortedArray[mid] < target) {
                left = mid +1;
            }
            else {
                right = mid +1;
            }
        }
        return -1;
    }
}
