/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertshiftarray;

public class Library {
    public static int[] insertShiftArray(int[] arr ,int value) {
        int middleindex =(int) Math.ceil(arr.length/2.0);
        int[] uppdatedArray = new int[arr.length+1];
        for(int i =0 , j=0;i<uppdatedArray.length;i++){
            if(i == middleindex) {
                uppdatedArray[i] = value;
            }
            else {
                uppdatedArray[i] = arr[j];
                j++;
            }
        }
        return uppdatedArray;
    }
}
