/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

import stack.queue.queue.Queue;
import stack.queue.stack.Stack;

public class App {

    public static void main(String[] args) {
        // Stack
        Stack<Integer> stack = new Stack<>();
        stack.isEmpty();
        System.out.println(stack.peek());
        stack.push(4);
        stack.push(45);
        stack.push(15);
        System.out.println(stack.peek());
        System.out.println("Stack : " + stack);
        //Queue

        Queue<Integer> queue = new Queue<>();
        queue.enqueue(4);
        queue.enqueue(6);
        queue.enqueue(45);
        System.out.println("Queue : " + queue);
    }
}
